### ISSUE TITLE
Controllers vibrate indefinitely after game close

### ISSUE THREAD

**Issue by jaylthegreat** [404-Name-Not-Found/dolphin#4]
https://bugs.dolphin-emu.org/issues/9001

**Comment by Kekker-git** [comment]
The issue has been fixed for GC controllers using the Wii U Adapter, but not any others.

Tried changing [this](https://github.com/dolphin-emu/dolphin/blob/0d078219358b04266206ea1e2622396db7724136/Source/Core/InputCommon/GCAdapter.cpp#L517) to
```
if (!UseAdapter() && (s_handle == nullptr || !s_detected))
```
but it is still somewhat buggy. More testing and researching needed.

**Comment by Kekker-git** [comment]
The aforementioned change has been reverted. Modifying GCPad worked a lot better, as rumble now stops on emulation close, but it does not stop on emulation pause.

**Comment by Kekker-git** [comment]
Fixed [here](https://github.com/404-Name-Not-Found/dolphin/commit/1d020e8ba47ce63138c326c27547a0dd5c63f934). Closed.
